# Generated by Django 4.0.4 on 2022-07-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('phone', models.IntegerField(default=0)),
                (
                    'address',
                    models.CharField(default='No registra ubicacion', max_length=250),
                ),
                (
                    'about',
                    models.CharField(default='No registra descripcion', max_length=250),
                ),
                (
                    'image',
                    models.URLField(
                        default='https://cdn.pixabay.com/photo/2018/04/18/18/56/user-3331256_960_720.png',
                    ),
                ),
                ('creation', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
