# Generated by Django 4.0.4 on 2022-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='petcategory',
            name='image',
            field=models.CharField(default='', max_length=180),
        ),
    ]
