# Generated by Django 4.0.4 on 2022-08-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_management', '0002_pet_age_pet_color_pet_sex_petcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sex',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
