# Generated by Django 4.0.4 on 2022-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                (
                    'address',
                    models.CharField(default='No registra ubicacion', max_length=100),
                ),
                (
                    'about',
                    models.CharField(default='No registra descripcion', max_length=200),
                ),
                (
                    'image',
                    models.URLField(
                        default='https://cdn.pixabay.com/photo/2018/04/18/18/56/user-3331256_960_720.png',
                    ),
                ),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
